baseUrl = "/"
languageCode = "en-us"
title = "Uğurcan Akkök"
theme = "hello-friend-ng"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

buildDrafts = false
buildFuture = false
buildExpired = false

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "02-01-2006"
  dateformNumTime = "02-01-2006 15:04 -0700"
  
  homeSubtitle = "An Enthusiastic Computer Engineering Student"
  # Metadata mostly used in document's head
  description = "Uğurcan Akkök's blogging website."
  keywords = "homepage, blog, computer science, development, programming, ugurcan akkok"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"

  #Social icons
  [[params.social]]
    name = "github"
    url = "https://github.com/UgurcanAkkok"

  [[params.social]]
    name = "linkedin"
    url = "https://linkedin.com/in/akkokugurcan"

  [[params.social]]
    name = "email"
    url = "mailto:akkokugurcan@gmail.com"
  
[languages]
  [languages.en]
    title = "Uğurcan Akkök"
    subtitle = ""
    keywords = ""
    copyright = "Uğurcan Akkök"
    readOtherPosts = "Read other posts"
 
  [languages.en.params.logo]
    logoText = "$ cd ~"
    logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"
 
 
# And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
